project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://rafaeell2304.github.io/projetos-novos/ # you must change this appropriately for RSS feeds to work properly
  title: "Projeto Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://rafaeell2304.github.io/projetos-novos/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: true




